In [37]:
import numpy as np
import pandas as pd

In [38]:
crime_data = pd.read_csv('Crime_data.csv',encoding='cp949')
crime_data.head()

     년도  구분  죄종 발생검거  건수
0  2011  중부  살인   발생   2
1  2011  중부  살인   검거   3
2  2011  중부  강도   발생  14
3  2011  중부  강도   검거  19
4  2011  중부  강간   발생  89

In [35]:
local=list(set(crime_data['구분']))
local
range(len(local))

range(0, 31)

In [36]:
years=range(2011,2019)

In [39]:
#서울시 각 구의 총 범죄 발생 건수
a=0
j=0
for j in range(len(local)):
    print()
    a=0
    for i in range(2011,2019):
        seoul=crime_data[crime_data['구분']==local[j]]
        seoul=seoul[seoul['년도']== i]
        seoul=seoul[seoul['발생검거']=='발생']
        a += seoul['건수'].sum()
    print(local[j],':',a)

강동 : 40146

도봉 : 22563

서부 : 16259

금천 : 29973

종암 : 14964

동대문 : 36678

남대문 : 15988

성동 : 25217

수서 : 27209

동작 : 30069

혜화 : 18234

노원 : 38231

마포 : 44483

영등포 : 53370

은평 : 22122

서초 : 32168

양천 : 34620

용산 : 31375

서대문 : 30509

강북 : 32050

중부 : 22597

강남 : 43415

방배 : 9898

종로 : 18826

성북 : 17862

관악 : 50438

중랑 : 41421

송파 : 55392

구로 : 43618

광진 : 44020

강서 : 44602

In [28]:
#서울시 각 구의 총 범죄 검거 건수
y=0
j=0
print("서울시 각 구의 총 범죄 검거 건수")
for j in range(len(local)):
    print()
    y=0
    for i in range(2011,2019):
        seoul=crime_data[crime_data['구분']==local[j]]
        seoul=seoul[seoul['년도']== i]
        seoul=seoul[seoul['발생검거']=='검거']
        y += seoul['건수'].sum()
    print(local[j],':',y)

서울시 각 구의 총 범죄 검거 건수

강동 : 25998

도봉 : 15324

서부 : 11193

금천 : 21424

종암 : 10128

동대문 : 25420

남대문 : 10603

성동 : 16302

수서 : 17247

동작 : 18159

혜화 : 12114

노원 : 24981

마포 : 26918

영등포 : 33030

은평 : 15085

서초 : 19958

양천 : 21514

용산 : 20962

서대문 : 19872

강북 : 23704

중부 : 13935

강남 : 27027

방배 : 6194

종로 : 12673

성북 : 11498

관악 : 30915

중랑 : 28718

송파 : 31332

구로 : 27560

광진 : 27906

강서 : 30065

In [31]:
#서울시 각 구의 총 범죄 검거율
a=0
j=0
y=0
city = []
per = []
for j in range(len(local)):
    print()
    a=0
    y=0
    for i in range(2011,2019):
        seoul=crime_data[crime_data['구분']==local[j]]
        seoul=seoul[seoul['년도']== i]
        seoul=seoul[seoul['발생검거']=='발생']
        a += seoul['건수'].sum()
        
        seoul=crime_data[crime_data['구분']==local[j]]
        seoul=seoul[seoul['년도']== i]
        seoul=seoul[seoul['발생검거']=='검거']
        y += seoul['건수'].sum()
    print(local[j],"검거율",':',round(y/a*100,2),'%')
    city.append(local[j])# 도시 이름 저장하는 배열
    per.append(round(y/a*100,2))# 검거율 저장하는 배열

강동 검거율 : 64.76 %

도봉 검거율 : 67.92 %

서부 검거율 : 68.84 %

금천 검거율 : 71.48 %

종암 검거율 : 67.68 %

동대문 검거율 : 69.31 %

남대문 검거율 : 66.32 %

성동 검거율 : 64.65 %

수서 검거율 : 63.39 %

동작 검거율 : 60.39 %

혜화 검거율 : 66.44 %

노원 검거율 : 65.34 %

마포 검거율 : 60.51 %

영등포 검거율 : 61.89 %

은평 검거율 : 68.19 %

서초 검거율 : 62.04 %

양천 검거율 : 62.14 %

용산 검거율 : 66.81 %

서대문 검거율 : 65.13 %

강북 검거율 : 73.96 %

중부 검거율 : 61.67 %

강남 검거율 : 62.25 %

방배 검거율 : 62.58 %

종로 검거율 : 67.32 %

성북 검거율 : 64.37 %

관악 검거율 : 61.29 %

중랑 검거율 : 69.33 %

송파 검거율 : 56.56 %

구로 검거율 : 63.18 %

광진 검거율 : 63.39 %

강서 검거율 : 67.41 %

In [32]:
gum_per = pd.DataFrame(per, index = city,columns = ['검거율'])
gum_per_sort = gum_per.sort_values(by=['검거율'], axis=0, ascending=False)
gum_per_sort

       검거율
강북   73.96
금천   71.48
중랑   69.33
동대문  69.31
서부   68.84
은평   68.19
도봉   67.92
종암   67.68
강서   67.41
종로   67.32
용산   66.81
혜화   66.44
남대문  66.32
노원   65.34
서대문  65.13
강동   64.76
성동   64.65
성북   64.37
수서   63.39
광진   63.39
구로   63.18
방배   62.58
강남   62.25
양천   62.14
서초   62.04
영등포  61.89
중부   61.67
관악   61.29
마포   60.51
동작   60.39
송파   56.56

In [18]:
gum_per_sort.mean()

검거율    65.049677
dtype: float64